-- copy it from the mysql script, remember to replace all 'lineage.' with an empty string

INSERT INTO bas_user (user_id, username, password, avatar, locked, create_time, modify_time, invalid) VALUES (1, 'demo', 'demo', 'iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAB2UlEQVR42u3bIW5CQRCA4XcYbNG4XqEBB6aiFkGCJ0FxIiQWEmwTDIbQA9QgySNzgZc8sRNYPvHrzc58dpr1rmlr6fN/2w7v16LFGzXNrAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOhqeRi036dZ8Ua3fXEA8UbGX2Jm1QCID5VeTG3FzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADoBxKlT6SaXVbs4fqhHMbOM3TQZmr/+NlXd02UUM8vYDQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAArw0g4/hgep5bas9iZimHIYb93gEAgCEAIAAEgAAQAAJAAAgAASAABIAAEAACQAAIAAEgAASAABAAAkAvDCBOkEr38ztOu6Yp/ZesK6eYWcZuqroNjFOn0n+JNxyHAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADPAOABx11T7Usu+c0AAAAASUVORK5CYII=', 0, 1674565178000, 1674565178000, 0);
INSERT INTO bas_user (user_id, username, password, avatar, locked, create_time, modify_time, invalid) VALUES (2, 'admin', 'admin', 'iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAABwklEQVR42u3dIQ4CMRAF0AoUHo3AEDSHQW4QJEiyCQIBCYIzcAcOgONqJXMBNhVtSPPE15P+vspJ027Y5l5yec3z/ZOqJmb01FkCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWgKIA/WSw3WVh3FTNTGjp85S7RfTMnFBtV9MzOipMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJjK7T2zGFKY6KwbAKfnwmpYYaIzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAnwCOj2Wunf15DUBhorMWd+PTqD8F4NcwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAqXy/WLeKhH4jDAAAAAElFTkSuQmCC', 0, 1674565178000, 1674565178000, 0);
INSERT INTO bas_user (user_id, username, password, avatar, locked, create_time, modify_time, invalid) VALUES (3, 'HamaWhite', '123456', 'iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAB1ElEQVR42u3dIYpCURSA4Zfcg2GKvDBBBqsMgm2SIGKaKYIbcR2TTDb34FLciXLsKoZz8D2+8OfLOferl9vMh9tLdrvJ7HJeDdLbtMv0WeKMilliZxV30wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3QUQB2V3mH0C8GKxs4q7aSqGqapPAKoCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB42HHe3haXXZxz+hmmVjlLbwDsv8cl79zigrJniTMqZomdAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwDMA2Q8pov/pl4chLxY7q7gbn0b5NQwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOB+v6P1baDsFh9/6bPEGRWzxM56A0DvGwAAWAIAAkAACAABIAAEgAAQAAJAAAgAASAABIAAEAACQAAIAAEgANTdrr/Kam2i+hYqAAAAAElFTkSuQmCC', 0, 1674565178000, 1674565178000, 0);
INSERT INTO bas_user (user_id, username, password, avatar, locked, create_time, modify_time, invalid) VALUES (4, 'Asteria', '123456', 'iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAB80lEQVR42u3bIW5CURAF0L8INoBiDZUkCFQFClNTDLKqClUUCgWqqvUYJKLJX0BFd8BKHpku4CcV80Jej7h6MneOne5h9llaybkfl59rl5qY0VJnHQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwFAWT7vyun1Oz9f3KB1AzKixS3TWDIBYKPswrSU6AwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+DcAXjbrsly9pSZmAHCnAOJA2bvEDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALgXANmPFJHd8RGAPyY6q3GbrqV3qpYA1AoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMBgTpfJ76tTdvbv83L4mKYmZtTYJTprBkAUV+PP7dyP03eJGTV2ic4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACGcgMMZ+UtKnNWWQAAAABJRU5ErkJggg==', 0, 1674565178000, 1674565178000, 0);
INSERT INTO bas_user (user_id, username, password, avatar, locked, create_time, modify_time, invalid) VALUES (5, 'Cattleya', '123456', 'iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAABxklEQVR42u3bIQpCQRCA4c3ewBuIJotZsXkBi0EEwSJYtBgMdsEqZq/5ZN4NDDv4Hl/48zCzX91yHU+a2q3Wm6a8PtXbLZbVd4kZGbvEzTLepgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACZAIb3R1O72eHUHq52o8ut+i4xI2OXuFnG25QMzdPjOUVzu1DlXWJGxi5xs4y3AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACg2wAyPh/Mt3sAfixulvIxJGOZrPoEICsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoMMA4gtSXxo839UBxIw+3Szlb6D+OEcAwBEAEAACQAAIAAEgAASAABAAAkAACAABIAAEgAAQAAJAAAgAAaDO9gWMGFcNBFkuLwAAAABJRU5ErkJggg==', 0, 1674565178000, 1674565178000, 0);

INSERT INTO bas_role (role_id, role_name, create_time, modify_time, invalid) VALUES (1, 'USER', 1674565178000, 1674565178000, 0);
INSERT INTO bas_role (role_id, role_name, create_time, modify_time, invalid) VALUES (2, 'ADMIN', 1674565178000, 1674565178000, 0);

INSERT INTO rel_role_user (rid, role_id, user_id, invalid) VALUES (1, 1, 1, 0);
INSERT INTO rel_role_user (rid, role_id, user_id, invalid) VALUES (2, 2, 2, 0);
INSERT INTO rel_role_user (rid, role_id, user_id, invalid) VALUES (3, 1, 3, 0);
INSERT INTO rel_role_user (rid, role_id, user_id, invalid) VALUES (4, 1, 4, 0);
INSERT INTO rel_role_user (rid, role_id, user_id, invalid) VALUES (5, 1, 5, 0);

INSERT INTO bas_permission (permission_id, permission_group, permission_name, permission_code, create_time, modify_time, invalid) VALUES (1, 'plugins', 'add plugin', 'system:plugin:add', 1674565178000, 1674565178000, 0);
INSERT INTO bas_permission (permission_id, permission_group, permission_name, permission_code, create_time, modify_time, invalid) VALUES (2, 'plugins', 'edit plugin', 'system:plugin:edit', 1674565178000, 1674565178000, 0);
INSERT INTO bas_permission (permission_id, permission_group, permission_name, permission_code, create_time, modify_time, invalid) VALUES (3, 'plugins', 'delete plugin', 'system:plugin:delete', 1674565178000, 1674565178000, 0);
INSERT INTO bas_permission (permission_id, permission_group, permission_name, permission_code, create_time, modify_time, invalid) VALUES (4, 'plugins', 'disable plugin', 'system:plugin:disable', 1674565178000, 1674565178000, 0);
INSERT INTO bas_permission (permission_id, permission_group, permission_name, permission_code, create_time, modify_time, invalid) VALUES (5, 'plugins', 'list plugin', 'system:plugin:list', 1674565178000, 1674565178000, 0);

INSERT INTO rel_role_permission (rid, role_id, permission_id, invalid) VALUES (1, 1, 5, 0);
INSERT INTO rel_role_permission (rid, role_id, permission_id, invalid) VALUES (2, 2, 1, 0);
INSERT INTO rel_role_permission (rid, role_id, permission_id, invalid) VALUES (3, 2, 2, 0);
INSERT INTO rel_role_permission (rid, role_id, permission_id, invalid) VALUES (4, 2, 3, 0);
INSERT INTO rel_role_permission (rid, role_id, permission_id, invalid) VALUES (5, 2, 4, 0);
INSERT INTO rel_role_permission (rid, role_id, permission_id, invalid) VALUES (6, 2, 5, 0);

INSERT INTO bas_plugin (plugin_id, plugin_name, plugin_code, descr, default_plugin, create_user_id, modify_user_id, create_time, modify_time, invalid) VALUES (1, 'Flink16', 'flink1.16.x', 'Field lineage plugin for flink1.16', 1, 2, 2, 1674565178000, 1674565178000, 0);
INSERT INTO bas_plugin (plugin_id, plugin_name, plugin_code, descr, default_plugin, create_user_id, modify_user_id, create_time, modify_time, invalid) VALUES (2, 'Flink14', 'flink1.14.x', 'Field lineage plugin for flink1.14', 0, 2, 2, 1674565178000, 1674565178000, 0);
INSERT INTO bas_plugin (plugin_id, plugin_name, plugin_code, descr, default_plugin, create_user_id, modify_user_id, create_time, modify_time, invalid) VALUES (3, 'Flink21', 'flink2.1.x', 'Field lineage plugin for flink2.1', 0, 2, 2, 1674565178000, 1674565178000, 0);

INSERT INTO bas_catalog (catalog_id, plugin_id, catalog_name, catalog_type, default_database, descr, properties, default_catalog, create_user_id, modify_user_id, create_time, modify_time, invalid) VALUES (1, 1, 'Flink16_memory', 'generic_in_memory', 'default', 'The MemoryCatalog is an in-memory implementation of a catalog. All objects will be available only for the lifetime of the session.', null, 1, 1, 1, 1674565178000, 1674565178000, 0);
INSERT INTO bas_catalog (catalog_id, plugin_id, catalog_name, catalog_type, default_database, descr, properties, default_catalog, create_user_id, modify_user_id, create_time, modify_time, invalid) VALUES (2, 3, 'Flink21_memory', 'generic_in_memory', 'default', 'The MemoryCatalog is an in-memory implementation of a catalog. All objects will be available only for the lifetime of the session.', null, 0, 1, 1, 1674565178000, 1674565178000, 0);

INSERT INTO bas_table (table_id, catalog_id, `database`, table_name, ddl, descr, create_user_id, modify_user_id, create_time, modify_time, invalid) VALUES (1, 1, 'default', 'ods_mysql_users', 'Q1JFQVRFIFRBQkxFIElGIE5PVCBFWElTVFMgb2RzX215c3FsX3VzZXJzICgKICAgIGlkIEJJR0lOVCBQUklNQVJZIEtFWSBOT1QgRU5GT1JDRUQsCiAgICBuYW1lIFNUUklORywKICAgIGJpcnRoZGF5IFRJTUVTVEFNUCgzKSwKICAgIHRzIFRJTUVTVEFNUCgzKSwKICAgIHByb2NfdGltZSBhcyBwcm9jdGltZSAoKQogICkKV0lUSAogICgKICAgICdjb25uZWN0b3InPSdteXNxbC1jZGMnLAogICAgJ2hvc3RuYW1lJz0nMTI3LjAuMC4xJywKICAgICdwb3J0Jz0nMzMwNicsCiAgICAndXNlcm5hbWUnPSdyb290JywKICAgICdwYXNzd29yZCc9J3h4eCcsCiAgICAnc2VydmVyLXRpbWUtem9uZSc9J0FzaWEvU2hhbmdoYWknLAogICAgJ2RhdGFiYXNlLW5hbWUnPSdkZW1vJywKICAgICd0YWJsZS1uYW1lJz0ndXNlcnMnCiAgKQ==', 'system built-in table', 1, 1, 1674565178000, 1674565178000, 0);
INSERT INTO bas_table (table_id, catalog_id, `database`, table_name, ddl, descr, create_user_id, modify_user_id, create_time, modify_time, invalid) VALUES (2, 1, 'default', 'dwd_hudi_users', 'Q1JFQVRFIFRBQkxFIElGIE5PVCBFWElTVFMKICBkd2RfaHVkaV91c2VycyAoCiAgICBpZCBCSUdJTlQgUFJJTUFSWSBLRVkgTk9UIEVORk9SQ0VELAogICAgbmFtZSBTVFJJTkcsCiAgICBjb21wYW55X25hbWUgU1RSSU5HLAogICAgYmlydGhkYXkgVElNRVNUQU1QKDMpLAogICAgdHMgVElNRVNUQU1QKDMpLAogICAgYHBhcnRpdGlvbmAgVkFSQ0hBUigyMCkKICApIFBBUlRJVElPTkVEIEJZIChgcGFydGl0aW9uYCkKV0lUSAogICgKICAgICdjb25uZWN0b3InPSdodWRpJywKICAgICd0YWJsZS50eXBlJz0nQ09QWV9PTl9XUklURScsCiAgICAncGF0aCcgPSAnL2h1ZGkvdXNlcnMnLAogICAgJ3JlYWQuc3RyZWFtaW5nLmVuYWJsZWQnPSd0cnVlJywKICAgICdyZWFkLnN0cmVhbWluZy5jaGVjay1pbnRlcnZhbCc9JzEnCiAgKQ==', 'system built-in table', 1, 1, 1674565178000, 1674565178000, 0);
INSERT INTO bas_table (table_id, catalog_id, `database`, table_name, ddl, descr, create_user_id, modify_user_id, create_time, modify_time, invalid) VALUES (3, 1, 'default', 'dim_mysql_company', 'Q1JFQVRFIFRBQkxFIElGIE5PVCBFWElTVFMgZGltX215c3FsX2NvbXBhbnkgKAogICAgdXNlcl9pZCBCSUdJTlQsCiAgICBjb21wYW55X25hbWUgU1RSSU5HCikgV0lUSCAoCiAgICAnY29ubmVjdG9yJz0namRiYycsCiAgICAndXJsJz0namRiYzpteXNxbDovLzEyNy4wLjAuMTozMzA2L2RlbW8/dXNlU1NMPWZhbHNlJmNoYXJhY3RlckVuY29kaW5nPVVURi04JywKICAgICd1c2VybmFtZSc9J3Jvb3QnLAogICAgJ3Bhc3N3b3JkJz0neHh4JywKICAgICd0YWJsZS1uYW1lJz0nY29tcGFueScKKQ==', 'system built-in table', 1, 1, 1674565178000, 1674565178000, 0);
INSERT INTO bas_table (table_id, catalog_id, `database`, table_name, ddl, descr, create_user_id, modify_user_id, create_time, modify_time, invalid) VALUES (4, 1, 'default', 'dws_users_cnt', 'Q1JFQVRFIFRBQkxFIElGIE5PVCBFWElTVFMgZHdzX3VzZXJzX2NudCAoIAogICAgaWQgQklHSU5UIFBSSU1BUlkgS0VZIE5PVCBFTkZPUkNFRCAsCiAgICBuYW1lX2NudCBCSUdJTlQgLCAKICAgIGNvbXBhbnlfbmFtZV9jbnQgQklHSU5UIAopV0lUSCAoIAogICAgJ2Nvbm5lY3RvcicgPSAnaHVkaScgLCAKICAgICd0YWJsZS50eXBlJyA9ICdNRVJHRV9PTl9SRUFEJyAKKSA=', 'system built-in table', 1, 1, 1674565178000, 1674565178000, 0);
INSERT INTO bas_table (table_id, catalog_id, `database`, table_name, ddl, descr, create_user_id, modify_user_id, create_time, modify_time, invalid) VALUES (5, 2, 'default', 'flink21_users_source', 'Q1JFQVRFIFRBQkxFIElGIE5PVCBFWElTVFMgZmxpbmsyMV91c2Vyc19zb3VyY2UgKAogICAgaWQgQklHSU5ULAogICAgbmFtZSBTVFJJTkcsCiAgICBiaXJ0aGRheSBUSU1FU1RBTVAoMyksCiAgICBzY29yZSBERUNJTUFMKDEwLCAyKSwKICAgIHByb2NfdGltZSBBUyBQUk9DVElNRSgpCikgV0lUSCAoCiAgICAnY29ubmVjdG9yJyA9ICdkYXRhZ2VuJwop', 'Flink 2.1 datagen source table', 1, 1, 1674565178000, 1674565178000, 0);
INSERT INTO bas_table (table_id, catalog_id, `database`, table_name, ddl, descr, create_user_id, modify_user_id, create_time, modify_time, invalid) VALUES (6, 2, 'default', 'flink21_company_source', 'Q1JFQVRFIFRBQkxFIElGIE5PVCBFWElTVFMgZmxpbmsyMV9jb21wYW55X3NvdXJjZSAoCiAgICB1c2VyX2lkIEJJR0lOVCwKICAgIGNvbXBhbnlfbmFtZSBTVFJJTkcKKSBXSVRIICgKICAgICdjb25uZWN0b3InID0gJ2RhdGFnZW4nCik=', 'Flink 2.1 datagen dimension source table', 1, 1, 1674565178000, 1674565178000, 0);
INSERT INTO bas_table (table_id, catalog_id, `database`, table_name, ddl, descr, create_user_id, modify_user_id, create_time, modify_time, invalid) VALUES (7, 2, 'default', 'flink21_users_sink', 'Q1JFQVRFIFRBQkxFIElGIE5PVCBFWElTVFMgZmxpbmsyMV91c2Vyc19zaW5rICgKICAgIGlkIEJJR0lOVCwKICAgIG5hbWUgU1RSSU5HLAogICAgY29tcGFueV9uYW1lIFNUUklORywKICAgIGJpcnRoZGF5IFRJTUVTVEFNUCgzKSwKICAgIHNjb3JlX3RleHQgU1RSSU5HLAogICAgcGFydGl0aW9uX2RheSBTVFJJTkcKKSBXSVRIICgKICAgICdjb25uZWN0b3InID0gJ2JsYWNraG9sZScKKQ==', 'Flink 2.1 blackhole user sink table', 1, 1, 1674565178000, 1674565178000, 0);
INSERT INTO bas_table (table_id, catalog_id, `database`, table_name, ddl, descr, create_user_id, modify_user_id, create_time, modify_time, invalid) VALUES (8, 2, 'default', 'flink21_stats_sink', 'Q1JFQVRFIFRBQkxFIElGIE5PVCBFWElTVFMgZmxpbmsyMV9zdGF0c19zaW5rICgKICAgIGlkIEJJR0lOVCwKICAgIG5hbWVfdXBwZXIgU1RSSU5HLAogICAgc2NvcmVfYnVja2V0IEJJR0lOVCwKICAgIGJpcnRoZGF5X2RheSBTVFJJTkcKKSBXSVRIICgKICAgICdjb25uZWN0b3InID0gJ2JsYWNraG9sZScKKQ==', 'Flink 2.1 blackhole transform sink table', 1, 1, 1674565178000, 1674565178000, 0);

INSERT INTO bas_task (task_id, catalog_id, task_name, descr, `database`, task_source, task_status, task_log, table_graph, column_graph, lineage_time, create_user_id, modify_user_id, create_time, modify_time, invalid) VALUES (1, 1, 'first-demo', 'Demo', 'default', 'SU5TRVJUIElOVE8KICAgIGR3ZF9odWRpX3VzZXJzClNFTEVDVAogICAgYS5pZCBhcyBpZDEsCiAgICBDT05DQVQoYS5uYW1lLGIuY29tcGFueV9uYW1lKSwKICAgIGIuY29tcGFueV9uYW1lLCAKICAgIGEuYmlydGhkYXksCiAgICBhLnRzLAogICAgREFURV9GT1JNQVQoYS5iaXJ0aGRheSwgJ3l5eXlNTWRkJykgYXMgcApGUk9NCiAgICBvZHNfbXlzcWxfdXNlcnMgQVMgYQpKT0lOCiAgICBkaW1fbXlzcWxfY29tcGFueSBGT1IgU1lTVEVNX1RJTUUgQVMgT0YgYS5wcm9jX3RpbWUgQVMgYiAKT04gYS5pZCA9IGIudXNlcl9pZDsKCklOU0VSVCBJTlRPIAogICAgZHdzX3VzZXJzX2NudCAKU0VMRUNUICAgICAgICAKICAgIGlkLCAgICAgICAKICAgIENPVU5UKERJU1RJTkNUIG5hbWUpLCAgICAgICAgCiAgICBDT1VOVChESVNUSU5DVCBjb21wYW55X25hbWUpIApGUk9NICAgICAgIAogICAgZHdkX2h1ZGlfdXNlcnMgCkdST1VQIEJZICAgICAgICAKICAgIGlk', 1, null, null, null, null, 1, 1, 1674565178000, 1691427210190, 0);
INSERT INTO bas_task (task_id, catalog_id, task_name, descr, `database`, task_source, task_status, task_log, table_graph, column_graph, lineage_time, create_user_id, modify_user_id, create_time, modify_time, invalid) VALUES (2, 1, 'join-demo', 'Join demo', 'default', 'SU5TRVJUIElOVE8KICAgIGR3ZF9odWRpX3VzZXJzClNFTEVDVAogICAgYS5pZCBhcyBpZDEgLAogICAgQ09OQ0FUKGEubmFtZSwgYi5jb21wYW55X25hbWUpICwgCiAgICBiLmNvbXBhbnlfbmFtZSAsIAogICAgYS5iaXJ0aGRheSAsCiAgICBhLnRzICwKICAgIERBVEVfRk9STUFUKGEuYmlydGhkYXksICd5eXl5TU1kZCcpIGFzIHAKRlJPTQogICAgb2RzX215c3FsX3VzZXJzIEFTIGEKSk9JTgogICAgZGltX215c3FsX2NvbXBhbnkgQVMgYgpPTiBhLmlkID0gYi51c2VyX2lk', 1, null, null, null, null, 1, 1, 1674565178000, 1691339187121, 0);
INSERT INTO bas_task (task_id, catalog_id, task_name, descr, `database`, task_source, task_status, task_log, table_graph, column_graph, lineage_time, create_user_id, modify_user_id, create_time, modify_time, invalid) VALUES (3, 1, 'lookup-join-demo', 'Lookup join demo', 'default', 'SU5TRVJUIElOVE8KICAgIGR3ZF9odWRpX3VzZXJzClNFTEVDVAogICAgYS5pZCBhcyBpZDEsCiAgICBDT05DQVQoYS5uYW1lLGIuY29tcGFueV9uYW1lKSwKICAgIGIuY29tcGFueV9uYW1lLCAKICAgIGEuYmlydGhkYXksCiAgICBhLnRzLAogICAgREFURV9GT1JNQVQoYS5iaXJ0aGRheSwgJ3l5eXlNTWRkJykgYXMgcApGUk9NCiAgICBvZHNfbXlzcWxfdXNlcnMgQVMgYQpKT0lOCiAgICBkaW1fbXlzcWxfY29tcGFueSBGT1IgU1lTVEVNX1RJTUUgQVMgT0YgYS5wcm9jX3RpbWUgQVMgYiAKT04gYS5pZCA9IGIudXNlcl9pZA==', 1, null, null, null, null, 1, 1, 1691338068375, 1691338191645, 0);
INSERT INTO bas_task (task_id, catalog_id, task_name, descr, `database`, task_source, task_status, task_log, table_graph, column_graph, lineage_time, create_user_id, modify_user_id, create_time, modify_time, invalid) VALUES (4, 1, 'udf-demo', 'UDF demo', 'default', 'SU5TRVJUIElOVE8KICAgIGR3ZF9odWRpX3VzZXJzClNFTEVDVAogICAgaWQsCiAgICBteV9zdWZmaXhfdWRmKG5hbWUpLAogICAgbmFtZSBhcyBjb21wYW55X25hbWUsIAogICAgYmlydGhkYXksCiAgICB0cywKICAgIERBVEVfRk9STUFUKGJpcnRoZGF5LCAneXl5eU1NZGQnKSAKRlJPTQogICAgb2RzX215c3FsX3VzZXJzCg==', 1, null, null, null, null, 1, 1, 1691338352066, 1691338715960, 0);
INSERT INTO bas_task (task_id, catalog_id, task_name, descr, `database`, task_source, task_status, task_log, table_graph, column_graph, lineage_time, create_user_id, modify_user_id, create_time, modify_time, invalid) VALUES (5, 1, 'abs_sum_demo', 'Complex transform demo', 'default', 'IElOU0VSVCBJTlRPIAogICAgZHdkX2h1ZGlfdXNlcnMKU0VMRUNUIAogICAgQUJTKHN1bV9pZCkgLAogICAgbmFtZSAsCiAgICBjb21wYW55X25hbWUgLAogICAgYmlydGhkYXkxICwKICAgIHRzICwKICAgIHAKRlJPTSAoCiAgICBTRUxFQ1QgCiAgICAgICAgU1VNKGlkKSBBUyBzdW1faWQgLAogICAgICAgIG5hbWUsCiAgICAgICAgJzEnIEFTIGNvbXBhbnlfbmFtZSAsCiAgICAgICAgTk9XKCkgQVMgYmlydGhkYXkxICwgCiAgICAgICAgTk9XKCkgQVMgdHMgLCAKICAgICAgICBEQVRFX0ZPUk1BVChiaXJ0aGRheSwgJ3l5eXlNTWRkJykgQVMgcApGUk9NIAogICAgb2RzX215c3FsX3VzZXJzCkdST1VQIEJZICAKICAgIG5hbWUsIAogICAgREFURV9GT1JNQVQoYmlydGhkYXksICd5eXl5TU1kZCcpKSA=', 1, null, null, null, null, 1, 1, 1691338980380, 1691339127608, 0);
INSERT INTO bas_task (task_id, catalog_id, task_name, descr, `database`, task_source, task_status, task_log, table_graph, column_graph, lineage_time, create_user_id, modify_user_id, create_time, modify_time, invalid) VALUES (6, 1, 'udtf-demo', 'UDTF demo', 'default', 'IElOU0VSVCBJTlRPIAogICAgZHdkX2h1ZGlfdXNlcnMKU0VMRUNUIAogICAgbGVuZ3RoICwKICAgIG5hbWUgLAogICAgd29yZCBBUyBjb21wYW55X25hbWUgLAogICAgYmlydGhkYXkgLAogICAgdHMgLAogICAgREFURV9GT1JNQVQoYmlydGhkYXksJ3l5eXlNTWRkJykKRlJPTSAKICAgIG9kc19teXNxbF91c2VycwpMRUZUIEpPSU4gCiAgICBMQVRFUkFMIFRBQkxFKG15X3NwbGl0X3VkdGYobmFtZSkpIE9OIFRSVUU=', 1, null, null, null, null, 1, 1, 1691339274970, 1691339482534, 0);
INSERT INTO bas_task (task_id, catalog_id, task_name, descr, `database`, task_source, task_status, task_log, table_graph, column_graph, lineage_time, create_user_id, modify_user_id, create_time, modify_time, invalid) VALUES (7, 2, 'flink21-basic-demo', 'Flink 2.1 projection and DATE_FORMAT demo', 'default', 'SU5TRVJUIElOVE8gZmxpbmsyMV91c2Vyc19zaW5rClNFTEVDVAogICAgaWQsCiAgICBuYW1lLAogICAgQ0FTVChOVUxMIEFTIFNUUklORyksCiAgICBiaXJ0aGRheSwKICAgIENBU1Qoc2NvcmUgQVMgU1RSSU5HKSwKICAgIERBVEVfRk9STUFUKGJpcnRoZGF5LCAneXl5eU1NZGQnKQpGUk9NIGZsaW5rMjFfdXNlcnNfc291cmNl', 1, null, null, null, null, 1, 1, 1783266500000, 1783266500000, 0);
INSERT INTO bas_task (task_id, catalog_id, task_name, descr, `database`, task_source, task_status, task_log, table_graph, column_graph, lineage_time, create_user_id, modify_user_id, create_time, modify_time, invalid) VALUES (8, 2, 'flink21-transform-demo', 'Flink 2.1 scalar transform lineage demo', 'default', 'SU5TRVJUIElOVE8gZmxpbmsyMV9zdGF0c19zaW5rClNFTEVDVAogICAgaWQsCiAgICBVUFBFUihuYW1lKSwKICAgIENBU1Qoc2NvcmUgLyAxMCBBUyBCSUdJTlQpLAogICAgREFURV9GT1JNQVQoYmlydGhkYXksICd5eXl5LU1NLWRkJykKRlJPTSBmbGluazIxX3VzZXJzX3NvdXJjZQ==', 1, null, null, null, null, 1, 1, 1783266500000, 1783266500000, 0);
INSERT INTO bas_task (task_id, catalog_id, task_name, descr, `database`, task_source, task_status, task_log, table_graph, column_graph, lineage_time, create_user_id, modify_user_id, create_time, modify_time, invalid) VALUES (9, 2, 'flink21-join-demo', 'Flink 2.1 join lineage demo', 'default', 'SU5TRVJUIElOVE8gZmxpbmsyMV91c2Vyc19zaW5rClNFTEVDVAogICAgdS5pZCwKICAgIHUubmFtZSwKICAgIGMuY29tcGFueV9uYW1lLAogICAgdS5iaXJ0aGRheSwKICAgIENBU1QodS5zY29yZSBBUyBTVFJJTkcpLAogICAgREFURV9GT1JNQVQodS5iaXJ0aGRheSwgJ3l5eXlNTWRkJykKRlJPTSBmbGluazIxX3VzZXJzX3NvdXJjZSBBUyB1CkpPSU4gZmxpbmsyMV9jb21wYW55X3NvdXJjZSBBUyBjCk9OIHUuaWQgPSBjLnVzZXJfaWQ=', 1, null, null, null, null, 1, 1, 1783266500000, 1783266500000, 0);

INSERT INTO bas_function (function_id, catalog_id, function_name, `database`, invocation, function_path, class_name, descr, create_user_id, modify_user_id, create_time, modify_time, invalid) VALUES (1, 1, 'my_suffix_udf', 'default', 'flink_suffix_udf(String1)', 'functions/function-a/function-a.jar', 'com.hw.flink.table.udf.functiona.FlinkSuffixFunction', 'return String', 1, 1, 1674565178000, 1674565178000, 0);
INSERT INTO bas_function (function_id, catalog_id, function_name, `database`, invocation, function_path, class_name, descr, create_user_id, modify_user_id, create_time, modify_time, invalid) VALUES (2, 1, 'my_prefix_udf', 'default', 'flink_prefix_udf(String1,Integer2)', 'functions/function-b/function-b.jar', 'com.hw.flink.table.udf.functionb.FlinkPrefixFunction', 'return String', 1, 1, 1674565178000, 1674565178000, 0);
INSERT INTO bas_function (function_id, catalog_id, function_name, `database`, invocation, function_path, class_name, descr, create_user_id, modify_user_id, create_time, modify_time, invalid) VALUES (3, 1, 'my_split_udtf', 'default', 'flink_split_udtf(String1)', 'functions/function-b/function-b.jar', 'com.hw.flink.table.udf.functionb.FlinkSplitFunction', 'return ROW<word STRING, length INT>', 1, 1, 1674565178000, 1674565178000, 0);
