
INSERT INTO lineage.bas_user (user_id, username, password, avatar, locked, create_time, modify_time, invalid) VALUES (1, 'demo', 'demo', 'iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAB2UlEQVR42u3bIW5CQRCA4XcYbNG4XqEBB6aiFkGCJ0FxIiQWEmwTDIbQA9QgySNzgZc8sRNYPvHrzc58dpr1rmlr6fN/2w7v16LFGzXNrAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOhqeRi036dZ8Ua3fXEA8UbGX2Jm1QCID5VeTG3FzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADoBxKlT6SaXVbs4fqhHMbOM3TQZmr/+NlXd02UUM8vYDQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAArw0g4/hgep5bas9iZimHIYb93gEAgCEAIAAEgAAQAAJAAAgAASAABIAAEAACQAAIAAEgAASAABAAAkAvDCBOkEr38ztOu6Yp/ZesK6eYWcZuqroNjFOn0n+JNxyHAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADPAOABx11T7Usu+c0AAAAASUVORK5CYII=', 0, 1674565178000, 1674565178000, 0);
INSERT INTO lineage.bas_user (user_id, username, password, avatar, locked, create_time, modify_time, invalid) VALUES (2, 'admin', 'admin', 'iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAABwklEQVR42u3dIQ4CMRAF0AoUHo3AEDSHQW4QJEiyCQIBCYIzcAcOgONqJXMBNhVtSPPE15P+vspJ027Y5l5yec3z/ZOqJmb01FkCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWgKIA/WSw3WVh3FTNTGjp85S7RfTMnFBtV9MzOipMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJjK7T2zGFKY6KwbAKfnwmpYYaIzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAnwCOj2Wunf15DUBhorMWd+PTqD8F4NcwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAqXy/WLeKhH4jDAAAAAElFTkSuQmCC', 0, 1674565178000, 1674565178000, 0);
INSERT INTO lineage.bas_user (user_id, username, password, avatar, locked, create_time, modify_time, invalid) VALUES (3, 'HamaWhite', '123456', 'iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAB1ElEQVR42u3dIYpCURSA4Zfcg2GKvDBBBqsMgm2SIGKaKYIbcR2TTDb34FLciXLsKoZz8D2+8OfLOferl9vMh9tLdrvJ7HJeDdLbtMv0WeKMilliZxV30wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3QUQB2V3mH0C8GKxs4q7aSqGqapPAKoCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB42HHe3haXXZxz+hmmVjlLbwDsv8cl79zigrJniTMqZomdAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwDMA2Q8pov/pl4chLxY7q7gbn0b5NQwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOB+v6P1baDsFh9/6bPEGRWzxM56A0DvGwAAWAIAAkAACAABIAAEgAAQAAJAAAgAASAABIAAEAACQAAIAAEgANTdrr/Kam2i+hYqAAAAAElFTkSuQmCC', 0, 1674565178000, 1674565178000, 0);
INSERT INTO lineage.bas_user (user_id, username, password, avatar, locked, create_time, modify_time, invalid) VALUES (4, 'Asteria', '123456', 'iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAB80lEQVR42u3bIW5CURAF0L8INoBiDZUkCFQFClNTDLKqClUUCgWqqvUYJKLJX0BFd8BKHpku4CcV80Jej7h6MneOne5h9llaybkfl59rl5qY0VJnHQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwFAWT7vyun1Oz9f3KB1AzKixS3TWDIBYKPswrSU6AwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+DcAXjbrsly9pSZmAHCnAOJA2bvEDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALgXANmPFJHd8RGAPyY6q3GbrqV3qpYA1AoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMBgTpfJ76tTdvbv83L4mKYmZtTYJTprBkAUV+PP7dyP03eJGTV2ic4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACGcgMMZ+UtKnNWWQAAAABJRU5ErkJggg==', 0, 1674565178000, 1674565178000, 0);
INSERT INTO lineage.bas_user (user_id, username, password, avatar, locked, create_time, modify_time, invalid) VALUES (5, 'Cattleya', '123456', 'iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAABxklEQVR42u3bIQpCQRCA4c3ewBuIJotZsXkBi0EEwSJYtBgMdsEqZq/5ZN4NDDv4Hl/48zCzX91yHU+a2q3Wm6a8PtXbLZbVd4kZGbvEzTLepgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACZAIb3R1O72eHUHq52o8ut+i4xI2OXuFnG25QMzdPjOUVzu1DlXWJGxi5xs4y3AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACg2wAyPh/Mt3sAfixulvIxJGOZrPoEICsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoMMA4gtSXxo839UBxIw+3Szlb6D+OEcAwBEAEAACQAAIAAEgAASAABAAAkAACAABIAAEgAAQAAJAAAgAAaDO9gWMGFcNBFkuLwAAAABJRU5ErkJggg==', 0, 1674565178000, 1674565178000, 0);

INSERT INTO lineage.bas_role (role_id, role_name, create_time, modify_time, invalid) VALUES (1, 'USER', 1674565178000, 1674565178000, 0);
INSERT INTO lineage.bas_role (role_id, role_name, create_time, modify_time, invalid) VALUES (2, 'ADMIN', 1674565178000, 1674565178000, 0);

INSERT INTO lineage.rel_role_user (rid, role_id, user_id, invalid) VALUES (1, 1, 1, 0);
INSERT INTO lineage.rel_role_user (rid, role_id, user_id, invalid) VALUES (2, 2, 2, 0);
INSERT INTO lineage.rel_role_user (rid, role_id, user_id, invalid) VALUES (3, 1, 3, 0);
INSERT INTO lineage.rel_role_user (rid, role_id, user_id, invalid) VALUES (4, 1, 4, 0);
INSERT INTO lineage.rel_role_user (rid, role_id, user_id, invalid) VALUES (5, 1, 5, 0);

INSERT INTO lineage.bas_permission (permission_id, permission_group, permission_name, permission_code, create_time, modify_time, invalid) VALUES (1, 'plugins', 'add plugin', 'system:plugin:add', 1674565178000, 1674565178000, 0);
INSERT INTO lineage.bas_permission (permission_id, permission_group, permission_name, permission_code, create_time, modify_time, invalid) VALUES (2, 'plugins', 'edit plugin', 'system:plugin:edit', 1674565178000, 1674565178000, 0);
INSERT INTO lineage.bas_permission (permission_id, permission_group, permission_name, permission_code, create_time, modify_time, invalid) VALUES (3, 'plugins', 'delete plugin', 'system:plugin:delete', 1674565178000, 1674565178000, 0);
INSERT INTO lineage.bas_permission (permission_id, permission_group, permission_name, permission_code, create_time, modify_time, invalid) VALUES (4, 'plugins', 'disable plugin', 'system:plugin:disable', 1674565178000, 1674565178000, 0);
INSERT INTO lineage.bas_permission (permission_id, permission_group, permission_name, permission_code, create_time, modify_time, invalid) VALUES (5, 'plugins', 'list plugin', 'system:plugin:list', 1674565178000, 1674565178000, 0);

INSERT INTO lineage.rel_role_permission (rid, role_id, permission_id, invalid) VALUES (1, 1, 5, 0);
INSERT INTO lineage.rel_role_permission (rid, role_id, permission_id, invalid) VALUES (2, 2, 1, 0);
INSERT INTO lineage.rel_role_permission (rid, role_id, permission_id, invalid) VALUES (3, 2, 2, 0);
INSERT INTO lineage.rel_role_permission (rid, role_id, permission_id, invalid) VALUES (4, 2, 3, 0);
INSERT INTO lineage.rel_role_permission (rid, role_id, permission_id, invalid) VALUES (5, 2, 4, 0);
INSERT INTO lineage.rel_role_permission (rid, role_id, permission_id, invalid) VALUES (6, 2, 5, 0);

INSERT INTO lineage.bas_plugin (plugin_id, plugin_name, plugin_code, descr, default_plugin, create_user_id, modify_user_id, create_time, modify_time, invalid) VALUES (1, 'Flink21', 'flink2.1.x', 'Field lineage plugin for flink2.1', 1, 2, 2, 1674565178000, 1674565178000, 0);

INSERT INTO lineage.bas_catalog (catalog_id, plugin_id, catalog_name, catalog_type, default_database, descr, properties, default_catalog, create_user_id, modify_user_id, create_time, modify_time, invalid) VALUES (1, 1, 'Flink21_memory', 'generic_in_memory', 'default', 'The MemoryCatalog is an in-memory implementation of a catalog. All objects will be available only for the lifetime of the session.', null, 1, 1, 1, 1674565178000, 1674565178000, 0);

INSERT INTO lineage.bas_table (table_id, catalog_id, `database`, table_name, ddl, descr, create_user_id, modify_user_id, create_time, modify_time, invalid) VALUES (1, 1, 'default', 'flink21_users_source', 'Q1JFQVRFIFRBQkxFIElGIE5PVCBFWElTVFMgZmxpbmsyMV91c2Vyc19zb3VyY2UgKAogICAgaWQgQklHSU5ULAogICAgbmFtZSBTVFJJTkcsCiAgICBiaXJ0aGRheSBUSU1FU1RBTVAoMyksCiAgICBzY29yZSBERUNJTUFMKDEwLCAyKSwKICAgIHByb2NfdGltZSBBUyBQUk9DVElNRSgpCikgV0lUSCAoCiAgICAnY29ubmVjdG9yJyA9ICdkYXRhZ2VuJwop', 'Flink 2.1 datagen source table', 1, 1, 1674565178000, 1674565178000, 0);
INSERT INTO lineage.bas_table (table_id, catalog_id, `database`, table_name, ddl, descr, create_user_id, modify_user_id, create_time, modify_time, invalid) VALUES (2, 1, 'default', 'flink21_company_source', 'Q1JFQVRFIFRBQkxFIElGIE5PVCBFWElTVFMgZmxpbmsyMV9jb21wYW55X3NvdXJjZSAoCiAgICB1c2VyX2lkIEJJR0lOVCwKICAgIGNvbXBhbnlfbmFtZSBTVFJJTkcKKSBXSVRIICgKICAgICdjb25uZWN0b3InID0gJ2RhdGFnZW4nCik=', 'Flink 2.1 datagen dimension source table', 1, 1, 1674565178000, 1674565178000, 0);
INSERT INTO lineage.bas_table (table_id, catalog_id, `database`, table_name, ddl, descr, create_user_id, modify_user_id, create_time, modify_time, invalid) VALUES (3, 1, 'default', 'flink21_users_sink', 'Q1JFQVRFIFRBQkxFIElGIE5PVCBFWElTVFMgZmxpbmsyMV91c2Vyc19zaW5rICgKICAgIGlkIEJJR0lOVCwKICAgIG5hbWUgU1RSSU5HLAogICAgY29tcGFueV9uYW1lIFNUUklORywKICAgIGJpcnRoZGF5IFRJTUVTVEFNUCgzKSwKICAgIHNjb3JlX3RleHQgU1RSSU5HLAogICAgcGFydGl0aW9uX2RheSBTVFJJTkcKKSBXSVRIICgKICAgICdjb25uZWN0b3InID0gJ2JsYWNraG9sZScKKQ==', 'Flink 2.1 blackhole user sink table', 1, 1, 1674565178000, 1674565178000, 0);
INSERT INTO lineage.bas_table (table_id, catalog_id, `database`, table_name, ddl, descr, create_user_id, modify_user_id, create_time, modify_time, invalid) VALUES (4, 1, 'default', 'flink21_stats_sink', 'Q1JFQVRFIFRBQkxFIElGIE5PVCBFWElTVFMgZmxpbmsyMV9zdGF0c19zaW5rICgKICAgIGlkIEJJR0lOVCwKICAgIG5hbWVfdXBwZXIgU1RSSU5HLAogICAgc2NvcmVfYnVja2V0IEJJR0lOVCwKICAgIGJpcnRoZGF5X2RheSBTVFJJTkcKKSBXSVRIICgKICAgICdjb25uZWN0b3InID0gJ2JsYWNraG9sZScKKQ==', 'Flink 2.1 blackhole transform sink table', 1, 1, 1674565178000, 1674565178000, 0);

INSERT INTO lineage.bas_task (task_id, catalog_id, task_name, descr, `database`, task_source, task_status, task_log, table_graph, column_graph, lineage_time, create_user_id, modify_user_id, create_time, modify_time, invalid) VALUES (1, 1, 'flink21-basic-demo', 'Flink 2.1 projection and DATE_FORMAT demo', 'default', 'SU5TRVJUIElOVE8gZmxpbmsyMV91c2Vyc19zaW5rClNFTEVDVAogICAgaWQsCiAgICBuYW1lLAogICAgQ0FTVChOVUxMIEFTIFNUUklORyksCiAgICBiaXJ0aGRheSwKICAgIENBU1Qoc2NvcmUgQVMgU1RSSU5HKSwKICAgIERBVEVfRk9STUFUKGJpcnRoZGF5LCAneXl5eU1NZGQnKQpGUk9NIGZsaW5rMjFfdXNlcnNfc291cmNl', 1, null, null, null, null, 1, 1, 1783266500000, 1783266500000, 0);
INSERT INTO lineage.bas_task (task_id, catalog_id, task_name, descr, `database`, task_source, task_status, task_log, table_graph, column_graph, lineage_time, create_user_id, modify_user_id, create_time, modify_time, invalid) VALUES (2, 1, 'flink21-transform-demo', 'Flink 2.1 scalar transform lineage demo', 'default', 'SU5TRVJUIElOVE8gZmxpbmsyMV9zdGF0c19zaW5rClNFTEVDVAogICAgaWQsCiAgICBVUFBFUihuYW1lKSwKICAgIENBU1Qoc2NvcmUgLyAxMCBBUyBCSUdJTlQpLAogICAgREFURV9GT1JNQVQoYmlydGhkYXksICd5eXl5LU1NLWRkJykKRlJPTSBmbGluazIxX3VzZXJzX3NvdXJjZQ==', 1, null, null, null, null, 1, 1, 1783266500000, 1783266500000, 0);
INSERT INTO lineage.bas_task (task_id, catalog_id, task_name, descr, `database`, task_source, task_status, task_log, table_graph, column_graph, lineage_time, create_user_id, modify_user_id, create_time, modify_time, invalid) VALUES (3, 1, 'flink21-join-demo', 'Flink 2.1 join lineage demo', 'default', 'SU5TRVJUIElOVE8gZmxpbmsyMV91c2Vyc19zaW5rClNFTEVDVAogICAgdS5pZCwKICAgIHUubmFtZSwKICAgIGMuY29tcGFueV9uYW1lLAogICAgdS5iaXJ0aGRheSwKICAgIENBU1QodS5zY29yZSBBUyBTVFJJTkcpLAogICAgREFURV9GT1JNQVQodS5iaXJ0aGRheSwgJ3l5eXlNTWRkJykKRlJPTSBmbGluazIxX3VzZXJzX3NvdXJjZSBBUyB1CkpPSU4gZmxpbmsyMV9jb21wYW55X3NvdXJjZSBBUyBjCk9OIHUuaWQgPSBjLnVzZXJfaWQ=', 1, null, null, null, null, 1, 1, 1783266500000, 1783266500000, 0);
