spring.application.version=${project.version}

server.port=8194

## DataSource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${MYSQL_URL:jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:lineage}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai}
spring.datasource.username=${MYSQL_USERNAME:root}
spring.datasource.password=${MYSQL_PASSWORD:}

## Servlet
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

## FlinkSQL Lineage
lineage.plugin.dir=${LINEAGE_PLUGIN_DIR:lineage-client/target/plugins}
lineage.storage.dir=${LINEAGE_STORAGE_DIR:data/storage}
lineage.security.permit-all-api=${LINEAGE_SECURITY_PERMIT_ALL_API:true}

## LOG
logging.file.path=${LINEAGE_LOG_DIR:data/logs}
